MedicalLocator.WebFront/Controllers/LoggingController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MedicalLocator.WebFront.Infrastructure;
using MedicalLocator.WebFront.Models;
using MedicalLocator.WebFront.Models.CommandsData;
using MedicalLocator.WebFront.Services;
using MedicalLocator.WebFront.ViewModels;

namespace MedicalLocator.WebFront.Controllers
{
    public class LoggingController : CommandsController
    {
        public LoggingController()
        {
        }

        public ActionResult ShowLoginDialog()
        {
            var viewModel = new LoginDataViewModel();
            return PartialView("_LoginDialogPartial", viewModel);
        }

        public ActionResult Login(string login, string password, bool rememberMe)
        {
            var loginDataViewModel = new LoginDataViewModel();
            loginDataViewModel.LoginData = new LoginData {Login = login, Password = password, RememberMe = rememberMe};

            if (!IsLoginDataViewModelValid(loginDataViewModel))
            {
                SetNotification(NotificationType.Error, "Some of the input data are invalid.");
                return FailureJsonResult();
            }

            SetNotification(NotificationType.Info, "Succesfully logged in as " + login);

            return ProcessCommandData(loginDataViewModel.LoginData,
                                      () => Json(LastCommandResult, JsonRequestBehavior.AllowGet));
        }

        public ActionResult Logout()
        {
            SetNotification(NotificationType.Info, "Logged out.");
            return ProcessCommandData(new LogoutData(), () => Json(LastCommandResult, JsonRequestBehavior.AllowGet));
        }

        private bool IsLoginDataViewModelValid(LoginDataViewModel loginDataViewModel)
        {
            return ModelState.IsValid && loginDataViewModel.LoginData.IsValid();
        }
    }
}

MedicalLocator.WebFront/Controllers/RegisteringController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MedicalLocator.WebFront.Infrastructure;
using MedicalLocator.WebFront.Models;
using MedicalLocator.WebFront.Models.CommandsData;
using MedicalLocator.WebFront.Services;
using MedicalLocator.WebFront.ViewModels;

namespace MedicalLocator.WebFront.Controllers
{
    public class RegisteringController : CommandsController
    {
        public RegisteringController()
        {
        }

        public ActionResult Register(string login, string password, string passwordRetype, bool licenceAgree)
        {
            var registerDataViewModel = new LoginDataViewModel();
            registerDataViewModel.RegisterData = new RegisterData { Login = login, Password = password, PasswordRetype = passwordRetype, LicenceAgree = licenceAgree};

            if (!IsRegisterDataViewModelValid(registerDataViewModel))
            {
                SetNotification(NotificationType.Error, "Some of the input data are invalid.");
                return FailureJsonResult();
            }

            SetNotification(NotificationType.Info, "Succesfully registered as " + login);

            return ProcessCommandData(registerDataViewModel.RegisterData, () => Json(LastCommandResult, JsonRequestBehavior.AllowGet));
        }

        private bool IsRegisterDataViewModelValid(LoginDataViewModel loginDataViewModel)
        {
            return ModelState.IsValid && loginDataViewModel.RegisterData.IsValid();
        }
    }
}

MedicalLocator.WebFront/Views/Logging/_LoginDialogPartial.cshtml
@using MedicalLocator.WebFront.ViewModels
@model LoginDataViewModel 

<div id="login_options_tabs">
    <ul>
        <li><a href="#tabs-login">Login</a></li>
        <li><a href="#tabs-register">Register</a></li>
    </ul>
    <div id="tabs-login">
        @Html.Partial("_LoginFormPartial", Model.LoginData)
    </div>
    <div id="tabs-register">
        @Html.Partial("_RegisterFormPartial", Model.RegisterData)
    </div>
</div>

MedicalLocator.WebFront/Views/Logging/_LoginFormPartial.cshtml
@model MedicalLocator.WebFront.Models.CommandsData.LoginData

@using (Ajax.BeginForm("Login", "Logging", null,
    new AjaxOptions { OnSuccess = "onLoginSuccess" },
    new { id = "login_form" }))
{
    @Html.FieldFor(model => model.Login)
    @Html.PassFor(model => model.Password)
    @Html.NamedCheckBoxFor("Remember me?", model => model.RememberMe)
}

<hr />

<button id="login_button">
    Login
</button>

<script type="text/javascript">
    function onLoginSuccess(response) {
        loggingDialogManager.processLoginResponse(response);
    }
    
    $(function () {
        $.validator.unobtrusive.parse(document);
        loggingDialogManager.initialize();
    });
</script>

MedicalLocator.WebFront/Views/Logging/_RegisterFormPartial.cshtml
@model MedicalLocator.WebFront.Models.CommandsData.RegisterData
           
@using (Ajax.BeginForm("Register", "Registering", null,
    new AjaxOptions { OnSuccess = "onRegisterSuccess" },
    new { id = "register_form" }))
{
    @Html.FieldFor(model => model.Login)
    @Html.PassFor(model => model.Password)
    @Html.PassFor(model => model.PasswordRetype)

    <p>
        <textarea rows="4" cols="60" readonly="readonly" style="font-size: 0.9em" >
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris id mauris at augue faucibus condimentum. Nulla quam felis, vehicula nec lacinia id, rutrum non enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis malesuada hendrerit purus, vitae varius sem ullamcorper nec. Morbi vitae odio quam. Ut accumsan eleifend lorem, non faucibus ante cursus in. Maecenas nisl augue, tincidunt at scelerisque nec, ultrices eu justo. Nam aliquet malesuada pulvinar. Vestibulum erat lacus, scelerisque non ultrices a, ultrices id sem. Mauris id mauris at augue faucibus condimentum. Nulla quam felis, vehicula nec lacinia id, rutrum non enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis malesuada hendrerit purus, vitae varius sem ullamcorper nec. Morbi vitae odio quam. Ut accumsan eleifend lorem, non faucibus ante cursus in. Maecenas nisl augue, tincidunt at scelerisque nec, ultrices eu justo. Nam aliquet malesuada pulvinar. Vestibulum erat lacus, scelerisque non ultrices a, ultrices id sem. Phasellus laoreet vestibulum tincidunt.
        </textarea>
   
        @Html.NamedCheckBoxFor("I have read and agree to the license agreement.", model => model.LicenceAgree)
    </p>
}

<hr />

<button id="register_button">
    Register
</button>

<script type="text/javascript">
    function onRegisterSuccess(response) {
        registeringDialogManager.processRegisterResponse(response);
    }

    $(function () {
        $.validator.unobtrusive.parse(document);
        registeringDialogManager.initialize();
    });
</script>