MedicalLocator.WebFront/Controllers/SearchingController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MedicalLocator.WebFront.Infrastructure;
using MedicalLocator.WebFront.Models;
using MedicalLocator.WebFront.Models.CommandsData;
using MedicalLocator.WebFront.Services;
using MedicalLocator.WebFront.ViewModels;

namespace MedicalLocator.WebFront.Controllers
{
    public class SearchingController : CommandsController
    {
        private readonly IEnumsValuesProvider _enumsValuesProvider;

        public SearchingController(IEnumsValuesProvider enumsValuesProvider)
        {
            _enumsValuesProvider = enumsValuesProvider;
        }

        public ActionResult FindNearby(double longitude, double latitude)
        {
            var findNearbyData = new FindNearbyData(longitude, latitude);
            return ProcessCommandData(findNearbyData, () => Json(LastCommandResult, JsonRequestBehavior.AllowGet));
        }

        public ActionResult ShowSearchDialog()
        {
            var viewModel = GetSearchDataViewModel();
            return PartialView("_SearchDialogPartial", viewModel);
        }

        public ActionResult Search(SearchDataViewModel searchDataViewModel)
        {
            if (!IsSearchDataViewModelValid(searchDataViewModel))
            {
                SetNotification(NotificationType.Error, "Some of the input data are invalid.");
                return FailureJsonResult();
            }

            IEnumerable<MedicalType> selectedMedicalTypes = searchDataViewModel.GetSelectedMedicalTypes();
            searchDataViewModel.SearchData.SearchedMedicalTypes = selectedMedicalTypes;

            SessionManager.LastSearchData = searchDataViewModel.SearchData;
            return ProcessCommandData(searchDataViewModel.SearchData, () => Json(LastCommandResult, JsonRequestBehavior.AllowGet));
        }

        private SearchDataViewModel GetSearchDataViewModel()
        {
            IEnumerable<CenterType> allCenterTypes = _enumsValuesProvider.GetAllCenterTypes();
            IEnumerable<MedicalType> allMedicalTypes = _enumsValuesProvider.GetAllMedicalTypes();

            SearchData lastSearchData = SessionManager.LastSearchData;
            if (lastSearchData != null)
            {
                return SearchDataViewModel.CreateUsingLastSearchData(allCenterTypes, allMedicalTypes, lastSearchData);
            }

            var medicalTypesDictionary = allMedicalTypes.ToDictionary(type => type, type => true);
            return new SearchDataViewModel(allCenterTypes, medicalTypesDictionary);
        }

        private bool IsSearchDataViewModelValid(SearchDataViewModel searchDataViewModel)
        {
            return ModelState.IsValid && searchDataViewModel.GetSelectedMedicalTypes().Any();
        }
    }
}

MedicalLocator.WebFront/Views/Searching/_SearchDialogPartial.cshtml
@using MedicalLocator.WebFront.ViewModels
@model SearchDataViewModel
           
@using (Ajax.BeginForm("Search", "Searching", null,
    new AjaxOptions { OnSuccess = "onSearchSuccess" },
    new { id = "search_form" }))
{
    @Html.HiddenFor(model => model.SearchData.UserLatitude)
    @Html.HiddenFor(model => model.SearchData.UserLongitude)
    
    <div id="search_options_tabs">
        <ul>
            <li><a href="#tabs-1">General</a></li>
            <li><a href="#tabs-2">Objects</a></li>
        </ul>
        <div id="tabs-1">
            @Html.Partial("_SearchGenralTabPartial", Model)
        </div>
        <div id="tabs-2">
            @Html.Partial("_SearchObjectsTabPartial", Model.MedicalTypesDictionary)
        </div>
    </div>
}
<hr />

<button id="search_button">
    Search
</button>
<script type="text/javascript">
    function onSearchSuccess(response) {
        searchingDialogManager.processSearchResponse(response);
    }

    $(function () {
        $.validator.unobtrusive.parse(document);
        searchingDialogManager.initialize();
    });
</script>

MedicalLocator.WebFront/Views/Searching/_SearchGenralTabPartial.cshtml
@model MedicalLocator.WebFront.ViewModels.SearchDataViewModel

@Html.FieldFor(model => model.SearchData.SearchingRange)
@Html.ComboBoxFor(model => model.SearchData.CenterType, new SelectList(Model.AllCenterTypes))
@Html.FieldFor(model => model.SearchData.SearchedAddress)
@Html.FieldFor(model => model.SearchData.SearchedLatitude)
@Html.FieldFor(model => model.SearchData.SearchedLongitude)

MedicalLocator.WebFront/Views/Searching/_SearchObjectsTabPartial.cshtml
@using MedicalLocator.WebFront.Models
@model IDictionary<MedicalType, bool>

<div id="medical_types_validation_div" class="validation-summary-valid">
    At least one medical type should be selected.
</div>

@for (int i = 0; i < Model.Count; i++)
{
    <div>
        @Html.CheckBox(string.Format("MedicalTypesDictionary[{0}].Value", i), Model.ElementAt(i).Value, new { @class = "medical_type_checkbox" })
        @Html.Label(string.Format("MedicalTypesDictionary[{0}].Key", i), Model.ElementAt(i).Key.ToString())
        @Html.Hidden(string.Format("MedicalTypesDictionary[{0}].Key", i), Model.ElementAt(i).Key.ToString())
    </div>
}